name: Validate release source

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    name: validate-source
    runs-on: ubuntu-latest

    steps:
      - name: Allow only develop
        if: github.head_ref != 'develop'
        run: |
          echo "main 브랜치에는 develop 브랜치에서만 PR을 생성할 수 있습니다."
          exit 1
